<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGehsWM1\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGehsWM1/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGehsWM1.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGehsWM1\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGehsWM1\App_KernelTestDebugContainer([
    'container.build_hash' => 'GehsWM1',
    'container.build_id' => '0ee1272e',
    'container.build_time' => 1694531654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGehsWM1');
