<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'accueil.index' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'admin.environnements' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminEnvironnementController::index'], [], [['text', '/admin/environnements']], [], [], []],
    'admin.environnement.suppr' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminEnvironnementController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/environnement/suppr']], [], [], []],
    'admin.environnement.ajout' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminEnvironnementController::ajout'], [], [['text', '/admin/environnement/ajout']], [], [], []],
    'admin.voyages' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminVoyagesController::index'], [], [['text', '/admin']], [], [], []],
    'admin.voyage.suppr' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminVoyagesController::suppr'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/suppr']], [], [], []],
    'admin.voyage.edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminVoyagesController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], [], []],
    'admin.voyage.ajout' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminVoyagesController::ajout'], [], [['text', '/admin/ajout']], [], [], []],
    'app_basefront' => [[], ['_controller' => 'App\\Controller\\BasefrontController::index'], [], [['text', '/basefront']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'voyages' => [[], ['_controller' => 'App\\Controller\\VoyagesController::index'], [], [['text', '/voyages']], [], [], []],
    'voyages.sort' => [['champ', 'ordre'], ['_controller' => 'App\\Controller\\VoyagesController::sort'], [], [['variable', '/', '[^/]++', 'ordre', true], ['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/tri']], [], [], []],
    'voyages.findallequal' => [['champ'], ['_controller' => 'App\\Controller\\VoyagesController::findAllEqual'], [], [['variable', '/', '[^/]++', 'champ', true], ['text', '/voyages/recherche']], [], [], []],
    'voyages.showone' => [['id'], ['_controller' => 'App\\Controller\\VoyagesController::showOne'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyages/voyage']], [], [], []],
];
