<?php

namespace Container8jgcqS0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLcWAC9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oLcWAC9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oLcWAC9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'environnement' => ['privates', '.errored..service_locator.oLcWAC9.App\\Entity\\Environnement', NULL, 'Cannot autowire service ".service_locator.oLcWAC9": it references class "App\\Entity\\Environnement" but no such service exists.'],
        ], [
            'environnement' => 'App\\Entity\\Environnement',
        ]);
    }
}
