<?php

namespace Container8jgcqS0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvironnementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oLcWAC9.App\Entity\Environnement' shared service.
     *
     * @return \App\Entity\Environnement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oLcWAC9": it references class "App\\Entity\\Environnement" but no such service exists.');
    }
}
