<?php

namespace ContainerF7EQvdc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOzuu7pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOzuu7p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOzuu7p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'visite' => ['privates', '.errored..service_locator.uOzuu7p.App\\Entity\\Visite', NULL, 'Cannot autowire service ".service_locator.uOzuu7p": it references class "App\\Entity\\Visite" but no such service exists.'],
        ], [
            'visite' => 'App\\Entity\\Visite',
        ]);
    }
}
