<?php

namespace ContainerF7EQvdc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminVoyagesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\admin\AdminVoyagesController' shared autowired service.
     *
     * @return \App\Controller\admin\AdminVoyagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'admin'.\DIRECTORY_SEPARATOR.'AdminVoyagesController.php';

        $container->services['App\\Controller\\admin\\AdminVoyagesController'] = $instance = new \App\Controller\admin\AdminVoyagesController(($container->privates['App\\Repository\\VisiteRepository'] ?? $container->load('getVisiteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\admin\\AdminVoyagesController', $container));

        return $instance;
    }
}
