<?php

namespace ContainerF7EQvdc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uOzuu7p.App\Entity\Visite' shared service.
     *
     * @return \App\Entity\Visite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uOzuu7p": it references class "App\\Entity\\Visite" but no such service exists.');
    }
}
