<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImrmDUw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImrmDUw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImrmDUw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImrmDUw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImrmDUw\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImrmDUw',
    'container.build_id' => 'c2ad7ec9',
    'container.build_time' => 1694250617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImrmDUw');
