<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container45XBiwj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container45XBiwj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container45XBiwj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container45XBiwj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container45XBiwj\App_KernelDevDebugContainer([
    'container.build_hash' => '45XBiwj',
    'container.build_id' => 'fdd9246e',
    'container.build_time' => 1694374306,
], __DIR__.\DIRECTORY_SEPARATOR.'Container45XBiwj');
