<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVc7St3J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVc7St3J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVc7St3J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVc7St3J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVc7St3J\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vc7St3J',
    'container.build_id' => 'be01f994',
    'container.build_time' => 1694102880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVc7St3J');
